### ISSUE TITLE
Cannot see how to specify IAM sudo group

### ISSUE THREAD

**Issue by nicklester** [cfn-modules/ssh-bastion#18]
As the template does not allow us to add custom tags to the EC2 instance as a property, I cannot see how to define a SUDOERS group when using IAMUserSSHAccess

Am I missing something?

**Comment by michaelwittig** [comment]
IAMUserSSHAccess doesn't support all features of https://github.com/widdix/aws-ec2-ssh#configuration It's a stripped down version of `aws-ec2-ssh`.

**But you don't want anyone to become root on the bastion host. This will allow the person to access all the other ssh tunnels.**

What's your use case? Maybe we can find a alternative solution?

**Comment by nicklester** [comment]
Hi - yeah I agree we don't want all users to have root - but I believe I have a use case where I need to dynamically manage groups of users to be able to access the bastion and periodically install different tooling (i.e. kafka utilities and tools in my case). I don't want to tie this down to one person, as I have a very redundant infrastructure in place - but don't want to make a single person on the team responsible for certain sys admin tasks...

**Comment by michaelwittig** [comment]
Ups, forget what I said about "IAMUserSSHAccess doesn't support all features of aws-ec2-ssh". It does The problem is that you can not configure it.

You should be able to do add tags like this:
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules example'
Resources:
  Bastion:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Tags:
      - Key: TAGKEY
        Value: TAGVALUE
      Parameters:
        VpcModule: !GetAtt 'Vpc.Outputs.StackName' # required
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName' # optional
        HostedZoneModule: !GetAtt 'HostedZone.Outputs.StackName' # optional
        KeyName: '' # optional
        IAMUserSSHAccess: false # optional
        InstanceType: 't2.nano' # optional
        LogGroupRetentionInDays: 14 # optional
        SubDomainNameWithDot: 'ssh.' # optional
      TemplateURL: './node_modules/@cfn-modules/ssh-bastion/module.yml'
```

But that won't help without the config.

I don't see a way to do it at the moment. Because of the security issues that all sudo users can access all ssh session I would recommend to use SSM / SSM State Manager do install additional software. The modules needs to be extended to support ssm. Similar to https://github.com/cfn-modules/asg-singleton-amazon-linux2/blob/master/module.yml#L43
